#!/usr/bin/env python3

import sys
import subprocess

with open("/tmp/out","a") as f:
    f.write("incoming: {}\n".format(" ".join(sys.argv)))

args = sys.argv[1:]



if "lstopo" in args:
    sys.exit(0)

if "-N" in args:
    del(args[args.index("-N")])

args = ["mpirun"] + args

with open("/tmp/out","a") as f:
    f.write("outgoing: {}\n".format(" ".join(args)))

pipe = subprocess.Popen( args )
sys.exit( pipe.wait())
